services:
  - type: web
    name: n8n-partyatmyplace
    env: docker
    plan: starter
    region: oregon
    branch: master
    autoDeploy: true
    healthCheckPath: /
    dockerfilePath: Dockerfile

    buildCommand: echo "Skipping build step"
    startCommand: tini -- n8n
